#!/usr/bin/env python3
"""Regenerate width_table.go from the installed Python wcwidth package.

The Go port measures display width with the same rules as the reference
implementation (Python's wcwidth) so wrapping positions are byte-identical.
Run from the repository root:

    python3 pkg/streamdown/tools/genwidth.py
"""
import json
import os
import sys

from wcwidth import wcwidth

OUT = os.path.join(os.path.dirname(__file__), "..", "width_table.go")


def classify():
    wide, zero = [], []
    for cp in range(0x110000):
        w = wcwidth(chr(cp))
        if w == 2:
            wide.append(cp)
        elif w == 0:
            zero.append(cp)
    return wide, zero


def to_ranges(points):
    out = []
    for cp in points:
        if out and cp == out[-1][1] + 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def emit(name, ranges):
    lines = [f"var {name} = []runeRange{{"]
    lines += [f"\t{{0x{a:04X}, 0x{b:04X}}}," for a, b in ranges]
    lines.append("}")
    return "\n".join(lines)


def main():
    if not (sys.version_info >= (3,) and "wcwidth" in sys.modules):
        import wcwidth  # noqa: F401  (import before classify)

    wide, zero = classify()
    header = """// Code generated by pkg/streamdown/tools/genwidth.py; DO NOT EDIT.
//
// Display-width tables matching Python's wcwidth package (the reference
// implementation's width source) so wrapping positions are identical.

package streamdown

type runeRange struct{ lo, hi rune }

func inRanges(r rune, tbl []runeRange) bool {
	for _, rg := range tbl {
		if r < rg.lo {
			return false
		}
		if r <= rg.hi {
			return true
		}
	}
	return false
}

// wcwidth reports the display width of r the way Python's wcwidth does:
// NUL is 0, control characters are -1, wide runes are 2, zero-width runes
// are 0, and everything else (including East Asian Ambiguous) is 1.
func wcwidth(r rune) int {
	if r == 0 {
		return 0
	}
	if (r >= 0x1 && r <= 0x1F) || (r >= 0x7F && r <= 0x9F) {
		return -1
	}
	if inRanges(r, wideRanges) {
		return 2
	}
	if inRanges(r, zeroWidthRanges) {
		return 0
	}
	return 1
}
"""
    body = header + "\n\n" + emit("wideRanges", to_ranges(wide)) + "\n\n" + emit("zeroWidthRanges", to_ranges(zero)) + "\n"
    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {OUT} ({len(body)} bytes, {len(wide)} wide / {len(zero)} zero points)")


if __name__ == "__main__":
    main()
