package streamdown

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// renderFixture renders a testdata file with the given width and plaintext
// mode and returns the raw bytes written to the output writer. images=false
// keeps ![alt](url) raw (the reference corpus comparison also disables image
// handling, since terminal image rendering is not portable).
func renderFixture(t *testing.T, name string, cfg Config) []byte {
	t.Helper()
	var buf bytes.Buffer
	r, err := New(&buf, cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	data, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := r.RenderString(string(data)); err != nil {
		t.Fatalf("RenderString: %v", err)
	}
	return buf.Bytes()
}

// TestGoldenANSIGo compares rendered output byte-for-byte against goldens
// generated by the reference Python implementation (pkg/streamdown/tools).
// The goldens cover headings, inline styles, lists, tables, blockquotes,
// links, rules and setext headings — everything except code-block syntax
// colours, which use a different (but equivalent) highlighter in Go.
func TestGoldenANSI(t *testing.T) {
	cases := []struct {
		fixture string
		golden  string
		width   int
	}{
		{"basic.md", "basic.ansi.golden", 80},
		{"cjk.md", "cjk.ansi.golden", 60},
	}
	for _, tc := range cases {
		t.Run(tc.fixture, func(t *testing.T) {
			// ANSI goldens are generated from the reference with tinted
			// backgrounds, so keep PlainBackground off for this comparison.
			cfg := DefaultConfig()
			cfg.Width = tc.width
			falseVal := false
			cfg.PlainBackground = &falseVal
			got := renderFixture(t, tc.fixture, cfg)
			want, err := os.ReadFile(filepath.Join("testdata", tc.golden))
			if err != nil {
				t.Fatalf("read golden: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("ANSI output mismatch\n--- got ---\n%q\n--- want ---\n%q", got, want)
			}
		})
	}
}

// TestGoldenPlaintext covers plaintext mode where ANSI is stripped, so code
// blocks (including the chroma-based highlighting) can be compared exactly.
func TestGoldenPlaintext(t *testing.T) {
	cases := []struct {
		fixture string
		golden  string
		width   int
		images  bool
	}{
		{"basic.md", "basic.plain.golden", 80, true},
		{"cjk.md", "cjk.plain.golden", 60, true},
		{"full.md", "full.plain.golden", 80, true},
		{"markdown-demo.md", "markdown-demo.plain.golden", 100, false},
	}
	for _, tc := range cases {
		t.Run(tc.fixture, func(t *testing.T) {
			cfg := DefaultConfig()
			cfg.Width = tc.width
			cfg.Plaintext = true
			// Python goldens keep the tinted pads, so use the reference look.
			falseVal := false
			cfg.PlainBackground = &falseVal
			if !tc.images {
				cfg.Images = &falseVal
			}
			got := renderFixture(t, tc.fixture, cfg)
			want, err := os.ReadFile(filepath.Join("testdata", tc.golden))
			if err != nil {
				t.Fatalf("read golden: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("plaintext output mismatch\n--- got ---\n%q\n--- want ---\n%q", got, want)
			}
		})
	}
}

// TestRenderIsStateless verifies that rendering multiple documents with one
// renderer produces the same output as a fresh renderer each time (no state
// leaks between documents).
func TestRenderIsStateless(t *testing.T) {
	fixtures := []string{"basic.md", "cjk.md", "full.md"}
	for _, name := range fixtures {
		t.Run(name, func(t *testing.T) {
			var first, second bytes.Buffer
			for _, buf := range []*bytes.Buffer{&first, &second} {
				cfg := DefaultConfig()
				cfg.Width = 80
				r, err := New(buf, cfg)
				if err != nil {
					t.Fatal(err)
				}
				data, err := os.ReadFile(filepath.Join("testdata", name))
				if err != nil {
					t.Fatal(err)
				}
				if err := r.RenderString(string(data)); err != nil {
					t.Fatal(err)
				}
			}
			if !bytes.Equal(first.Bytes(), second.Bytes()) {
				t.Errorf("state leaked between renders")
			}
		})
	}
}

// TestRenderString trivially wraps Render and must behave identically.
func TestRenderString(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Width = 60
	cfg.Plaintext = true
	var a, b bytes.Buffer
	ra, _ := New(&a, cfg)
	rb, _ := New(&b, cfg)
	src := "# 标题\n\n正文 **加粗** 内容。\n"
	if err := ra.RenderString(src); err != nil {
		t.Fatal(err)
	}
	if err := rb.Render(strings.NewReader(src)); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(a.Bytes(), b.Bytes()) {
		t.Errorf("RenderString != Render")
	}
}
