// Package streamdown renders markdown to a terminal as streaming ANSI text.
// It is a Go port of Streamdown
// (https://github.com/day50-dev/render-markdown-terminal): the same palette
// (HSV-derived true colours), CJK-aware wrapping, fenced/indented code blocks
// with syntax highlighting, tables, nested lists, blockquotes, setext and ATX
// headings, horizontal rules, inline styles, OSC 8 hyperlinks and OSC 52
// clipboard on exit.
//
// The renderer streams: Render reads input incrementally (byte by byte) and
// writes each finished chunk as soon as it is available, so output appears in
// real time while the input is still coming in — exactly what an LLM
// stream-to-terminal pipeline wants.
//
// # Fidelity
//
// Output is byte-identical to the reference (with PlainBackground off and the
// same palette) for everything outside code blocks (verified against goldens
// generated by the Python implementation, see pkg/streamdown/tools and
// testdata/). Four deliberate differences:
//
//   - PlainBackground defaults to on: code blocks, tables and inline code use
//     the terminal default background instead of the theme's Dark/Mid tint
//     (which the reference paints; dark maroon with the default hue). Set
//     PlainBackground=false for the reference look.
//   - Code-block syntax highlighting uses chroma instead of pygments, so token
//     colours differ (the structure — pads, wrapping — matches).
//   - Terminal images are not drawn; ![alt](url) falls back to the alt text.
//   - Degenerate inputs the reference itself mangles (NUL bytes, CJK-heavy
//     docstrings inside code blocks) may be mangled in a slightly different
//     way, since the incremental highlighter's token boundaries differ.
package streamdown

import (
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"golang.org/x/term"
)

// ColorMult and HSV are defined in style.go; Config below is the zero-value
// safe way to tune a renderer. Every field falls back to the reference
// implementation's defaults when left at its zero value.

// Config tunes the renderer. The zero value is valid and means "reference
// defaults" (margin 2, ListIndent 2, HSV {0.8, 0.5, 0.5}, all features on).
// To turn a default-on feature off, build on DefaultConfig.
type Config struct {
	Width      int // content width in columns; 0 → terminal width (80 when not a TTY)
	Margin     int // left/right margin; 0 → 2
	ListIndent int // recursive list indent; 0 → 2

	HSV [3]float64 // base hue/saturation/value; all-zero → {0.8, 0.5, 0.5}

	// Palette multipliers applied over HSV (zero ColorMult → reference default).
	Dark   ColorMult
	Mid    ColorMult
	Symbol ColorMult
	Head   ColorMult
	Grey   ColorMult
	Bright ColorMult

	Syntax string // chroma style name for code blocks; "" → "native"
	Prompt string // regexp detecting a streaming prompt; "" → `^.*>\s+$`

	Links           *bool // OSC 8 hyperlinks; nil → true
	Images          *bool // image fallback text; nil → true
	CodeSpaces      *bool // 4-space indented code blocks; nil → false
	Clipboard       *bool // OSC 52 clipboard of the last code block; nil → true
	Savebrace       *bool // append code blocks to $TMP/sd/<uid>/savebrace; nil → false
	PrettyPad       *bool // half-block background pads around code; nil → true
	PrettyBroken    *bool // wrap long code lines (breaks copy/paste); nil → true
	PlainBackground *bool // code/table/inline-code use terminal default background (no tint); nil → true
	Plaintext       bool  // strip all ANSI, output plain text only
}

// DefaultConfig returns the reference implementation's default settings.
func DefaultConfig() Config {
	true_, false_ := true, false
	return Config{
		Margin:          2,
		ListIndent:      2,
		HSV:             [3]float64{0.8, 0.5, 0.5},
		Dark:            ColorMult{H: 1.00, S: 1.50, V: 0.25},
		Mid:             ColorMult{H: 1.00, S: 1.00, V: 0.50},
		Symbol:          ColorMult{H: 1.00, S: 1.00, V: 1.50},
		Head:            ColorMult{H: 1.00, S: 1.00, V: 1.75},
		Grey:            ColorMult{H: 1.00, S: 0.25, V: 1.37},
		Bright:          ColorMult{H: 1.00, S: 0.60, V: 2.00},
		Syntax:          "native",
		Prompt:          `^.*>\s+$`,
		Links:           &true_,
		Images:          &true_,
		CodeSpaces:      &false_,
		Clipboard:       &true_,
		Savebrace:       &false_,
		PrettyPad:       &true_,
		PrettyBroken:    &true_,
		PlainBackground: &true_,
	}
}

// Renderer renders markdown to an io.Writer. Create it with New, then call
// Render/RenderString for each document and Tidyup when done.
type Renderer struct {
	Style *Style
	state *ParseState
	out   io.Writer

	cfg       Config
	widthArg  int
	termWidth int
	promptRe  *regexp.Regexp
}

// New creates a renderer. With no arguments it uses DefaultConfig; at most one
// Config may be given and its non-zero fields override the defaults. It is
// safe to call New concurrently; each Renderer must be used from one
// goroutine at a time.
func New(out io.Writer, cfg ...Config) (*Renderer, error) {
	if out == nil {
		out = os.Stdout
	}
	if len(cfg) > 1 {
		return nil, fmt.Errorf("streamdown: New accepts at most one Config")
	}
	c := DefaultConfig()
	if len(cfg) == 1 {
		merge(&c, cfg[0])
	}
	return newRenderer(c, out)
}

// boolOr dereferences a pointer option, falling back to def when nil.
func boolOr(v *bool, def bool) bool {
	if v == nil {
		return def
	}
	return *v
}

// merge overlays the non-zero fields of over onto base.
func merge(base *Config, over Config) {
	if over.Width != 0 {
		base.Width = over.Width
	}
	if over.Margin != 0 {
		base.Margin = over.Margin
	}
	if over.ListIndent != 0 {
		base.ListIndent = over.ListIndent
	}
	if over.HSV != [3]float64{} {
		base.HSV = over.HSV
	}
	if over.Dark != (ColorMult{}) {
		base.Dark = over.Dark
	}
	if over.Mid != (ColorMult{}) {
		base.Mid = over.Mid
	}
	if over.Symbol != (ColorMult{}) {
		base.Symbol = over.Symbol
	}
	if over.Head != (ColorMult{}) {
		base.Head = over.Head
	}
	if over.Grey != (ColorMult{}) {
		base.Grey = over.Grey
	}
	if over.Bright != (ColorMult{}) {
		base.Bright = over.Bright
	}
	if over.Syntax != "" {
		base.Syntax = over.Syntax
	}
	if over.Prompt != "" {
		base.Prompt = over.Prompt
	}
	if over.Links != nil {
		base.Links = over.Links
	}
	if over.Images != nil {
		base.Images = over.Images
	}
	if over.CodeSpaces != nil {
		base.CodeSpaces = over.CodeSpaces
	}
	if over.Clipboard != nil {
		base.Clipboard = over.Clipboard
	}
	if over.Savebrace != nil {
		base.Savebrace = over.Savebrace
	}
	if over.PrettyPad != nil {
		base.PrettyPad = over.PrettyPad
	}
	if over.PrettyBroken != nil {
		base.PrettyBroken = over.PrettyBroken
	}
	if over.PlainBackground != nil {
		base.PlainBackground = over.PlainBackground
	}
	base.Plaintext = over.Plaintext
}

func newRenderer(cfg Config, out io.Writer) (*Renderer, error) {
	r := &Renderer{out: out, cfg: cfg}
	if cfg.Prompt != "" {
		re, err := regexp.Compile(cfg.Prompt)
		if err != nil {
			return nil, fmt.Errorf("streamdown: invalid Prompt regexp %q: %w", cfg.Prompt, err)
		}
		r.promptRe = re
	}
	r.setup()
	return r, nil
}

func (r *Renderer) setup() {
	cfg := r.cfg

	// Terminal width: explicit width wins, else the real terminal, else 80.
	r.widthArg = cfg.Width
	r.termWidth = cfg.Width
	if r.termWidth == 0 {
		if f, ok := r.out.(*os.File); ok && term.IsTerminal(int(f.Fd())) {
			if w, _, err := term.GetSize(int(f.Fd())); err == nil && w > 0 {
				r.termWidth = w
			}
		}
	}
	if r.termWidth == 0 {
		r.termWidth = 80
	}

	h, s, v := cfg.HSV[0], cfg.HSV[1], cfg.HSV[2]

	st := &Style{
		Dark:            applyMultipliers(cfg.Dark, h, s, v),
		Mid:             applyMultipliers(cfg.Mid, h, s, v),
		Symbol:          applyMultipliers(cfg.Symbol, h, s, v),
		Head:            applyMultipliers(cfg.Head, h, s, v),
		Grey:            applyMultipliers(cfg.Grey, h, s, v),
		Bright:          applyMultipliers(cfg.Bright, h, s, v),
		Margin:          cfg.Margin,
		ListIndent:      cfg.ListIndent,
		PrettyPad:       boolOr(cfg.PrettyPad, true),
		PrettyBroken:    boolOr(cfg.PrettyBroken, true),
		PlainBackground: boolOr(cfg.PlainBackground, true),
		Syntax:          cfg.Syntax,
		Plaintext:       cfg.Plaintext,
		CodeSpaces:      boolOr(cfg.CodeSpaces, false),
		Images:          boolOr(cfg.Images, true),
		Links:           boolOr(cfg.Links, true),
	}
	st.Codebg = ANSIBG + st.Dark
	st.Link = ANSIFG + st.Symbol + underline[0]
	st.Blockquote = ANSIFG + st.Grey + "│ "
	st.MarginSpaces = strings.Repeat(" ", st.Margin)

	r.Style = st
	r.state = newParseState(st)
	r.widthCalc()
}

// widthCalc recomputes the content width and the code-block pads. It runs on
// every emitted chunk so streaming list/blockquote indentation stays current.
func (r *Renderer) widthCalc() {
	s := r.state
	if r.widthArg > 0 {
		s.widthFull = r.widthArg
		s.widthWrap = false
	} else {
		s.widthFull = r.termWidth
		s.widthWrap = r.termWidth != 80
	}
	s.width = s.widthFull - 2*r.Style.Margin
	if s.width < 1 {
		s.width = 1
	}

	pre := ""
	if r.Style.PrettyBroken {
		pre = s.spaceLeft(true)
	}
	full := s.fullWidth(0)
	if r.Style.PrettyPad {
		r.Style.Codepad = [2]string{
			pre + ANSIReset + ANSIFG + r.Style.Dark + strings.Repeat("▄", full) + ANSIReset + "\n",
			pre + ANSIReset + ANSIFG + r.Style.Dark + strings.Repeat("▀", full) + ANSIReset,
		}
	} else {
		r.Style.Codepad = [2]string{
			pre + ANSIReset + ANSIBG + r.Style.Dark + strings.Repeat(" ", full) + ANSIReset + "\n",
			pre + ANSIReset + ANSIBG + r.Style.Dark + strings.Repeat(" ", full) + ANSIReset,
		}
	}
}

// StripANSI removes ANSI escape sequences from s. It is exported for
// callers that need a plain view of rendered output.
func StripANSI(s string) string {
	return stripANSI(s)
}

// Render streams markdown from input to the renderer's writer.
func (r *Renderer) Render(input io.Reader) error {
	r.state = newParseState(r.Style)
	r.widthCalc()
	r.emit(input)
	return nil
}

// RenderString renders markdown from a string.
func (r *Renderer) RenderString(s string) error {
	return r.Render(strings.NewReader(s))
}

// emit drives the parser and the one-chunk look-ahead buffer, so setext
// headings ("Heading\n---") and streaming prompt flushes can rewrite the
// buffered chunk before it reaches the output.
func (r *Renderer) emit(input io.Reader) {
	buffer := make([]string, 0, 4)
	flush := false

	r.parse(input, func(chunk string) {
		r.widthCalc()

		if r.state.emitFlag != EmitNone {
			switch r.state.emitFlag {
			case EmitFlush:
				flush = true
				r.state.emitFlag = EmitNone
			default: // setext heading levels 1/2
				if len(buffer) > 0 {
					buffer[0] = r.emitH(int(r.state.emitFlag), buffer[0])
				}
				r.state.emitFlag = EmitNone
				return
			}
		}

		if !r.state.hasNewline {
			chunk = strings.TrimRight(chunk, "\n")
		} else if !strings.HasSuffix(chunk, "\n") {
			chunk += "\n"
		}

		if strings.HasSuffix(chunk, "\n") {
			r.state.currentLine = ""
		} else {
			r.state.currentLine += chunk
		}

		buffer = append(buffer, chunk)
		r.state.resetInline()

		switch {
		case flush:
			chunk = strings.Join(buffer, "\n")
			buffer = buffer[:0]
			flush = false
		case len(buffer) == 1:
			return
		default:
			chunk = buffer[0]
			buffer = buffer[1:]
		}
		r.write(r.terminalPrep(chunk))
	})

	if len(buffer) > 0 {
		r.write(r.terminalPrep(buffer[0]))
	}
}

// write emits a chunk to the output.
func (r *Renderer) write(s string) {
	if s == "" {
		return
	}
	_, _ = io.WriteString(r.out, s)
}

// terminalPrep strips ANSI codes and right-margin padding in plaintext mode.
func (r *Renderer) terminalPrep(what string) string {
	if !r.Style.Plaintext {
		return what
	}
	lines := strings.Split(stripANSI(what), "\n")
	for i, l := range lines {
		lines[i] = strings.TrimRight(l, " ")
	}
	out := strings.Join(lines, "\n")
	if strings.TrimSpace(out) == "" {
		return ""
	}
	return out
}

// Tidyup returns the terminal to normal: restores the palette and, if the
// Clipboard feature is on and a code block was seen, sends it to the system
// clipboard via OSC 52.
func (r *Renderer) Tidyup() {
	s := r.state
	if boolOr(r.cfg.Clipboard, true) && s.codeBufferRaw != "" {
		if f, ok := r.out.(*os.File); ok && term.IsTerminal(int(f.Fd())) {
			code := base64.StdEncoding.EncodeToString([]byte(s.codeBufferRaw))
			r.write("\x1b]52;c;" + code + "\a")
		}
	}
	r.write(ANSIReset)
}

// savebrace appends the current code block to the shared savebrace file so
// other tools (e.g. fzf) can pick it up, mirroring the reference behaviour.
func (r *Renderer) savebrace() {
	s := r.state
	if !boolOr(r.cfg.Savebrace, false) || s.codeBufferRaw == "" {
		return
	}
	dir := filepath.Join(os.TempDir(), "sd", fmt.Sprint(os.Getuid()))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	f, err := os.OpenFile(filepath.Join(dir, "savebrace"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	_, _ = f.WriteString(s.codeBufferRaw + "\x00")
}
